<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PredictiveBudget.Application\PredictiveBudget.Application.csproj" />
    <ProjectReference Include="..\PredictiveBudget.Domain\PredictiveBudget.Domain.csproj" />
  </ItemGroup>
</Project>
