<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PredictiveBudget.Web\PredictiveBudget.Web.csproj" />
    <ProjectReference Include="..\..\src\PredictiveBudget.Application\PredictiveBudget.Application.csproj" />
    <ProjectReference Include="..\..\src\PredictiveBudget.Domain\PredictiveBudget.Domain.csproj" />
    <ProjectReference Include="..\..\src\PredictiveBudget.Persistence\PredictiveBudget.Persistence.csproj" />
  </ItemGroup>

</Project>
