<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <RequiresAspNetWebAssets>true</RequiresAspNetWebAssets>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PredictiveBudget.Application\PredictiveBudget.Application.csproj" />
    <ProjectReference Include="..\PredictiveBudget.Domain\PredictiveBudget.Domain.csproj" />
    <ProjectReference Include="..\PredictiveBudget.Persistence\PredictiveBudget.Persistence.csproj" />
  </ItemGroup>
</Project>
